\section{Context\+Error\+Exception Class Reference}
\label{class_symfony_1_1_component_1_1_debug_1_1_exception_1_1_context_error_exception}\index{Context\+Error\+Exception@{Context\+Error\+Exception}}
Inheritance diagram for Context\+Error\+Exception\+:\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[height=2.000000cm]{class_symfony_1_1_component_1_1_debug_1_1_exception_1_1_context_error_exception}
\end{center}
\end{figure}
\subsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
{\bf \+\_\+\+\_\+construct} (\$message, \$code, \$severity, \$filename, \$lineno, \$context=array())
\item 
{\bf get\+Context} ()
\end{DoxyCompactItemize}


\subsection{Detailed Description}
\doxyref{Error}{p.}{class_error} \doxyref{Exception}{p.}{namespace_symfony_1_1_component_1_1_debug_1_1_exception} with Variable Context.

\begin{DoxyAuthor}{Author}
Christian Sciberras {\tt uuf6429@gmail.\+com} 
\end{DoxyAuthor}


Definition at line 19 of file Context\+Error\+Exception.\+php.



\subsection{Constructor \& Destructor Documentation}
\index{Symfony\+::\+Component\+::\+Debug\+::\+Exception\+::\+Context\+Error\+Exception@{Symfony\+::\+Component\+::\+Debug\+::\+Exception\+::\+Context\+Error\+Exception}!\+\_\+\+\_\+construct@{\+\_\+\+\_\+construct}}
\index{\+\_\+\+\_\+construct@{\+\_\+\+\_\+construct}!Symfony\+::\+Component\+::\+Debug\+::\+Exception\+::\+Context\+Error\+Exception@{Symfony\+::\+Component\+::\+Debug\+::\+Exception\+::\+Context\+Error\+Exception}}
\subsubsection[{\+\_\+\+\_\+construct}]{\setlength{\rightskip}{0pt plus 5cm}\+\_\+\+\_\+construct (
\begin{DoxyParamCaption}
\item[{}]{\$message, }
\item[{}]{\$code, }
\item[{}]{\$severity, }
\item[{}]{\$filename, }
\item[{}]{\$lineno, }
\item[{}]{\$context = {\ttfamily array()}}
\end{DoxyParamCaption}
)}\label{class_symfony_1_1_component_1_1_debug_1_1_exception_1_1_context_error_exception_a0f4188c2860a81505f294f61ab38be7d}


Definition at line 23 of file Context\+Error\+Exception.\+php.



\subsection{Member Function Documentation}
\index{Symfony\+::\+Component\+::\+Debug\+::\+Exception\+::\+Context\+Error\+Exception@{Symfony\+::\+Component\+::\+Debug\+::\+Exception\+::\+Context\+Error\+Exception}!get\+Context@{get\+Context}}
\index{get\+Context@{get\+Context}!Symfony\+::\+Component\+::\+Debug\+::\+Exception\+::\+Context\+Error\+Exception@{Symfony\+::\+Component\+::\+Debug\+::\+Exception\+::\+Context\+Error\+Exception}}
\subsubsection[{get\+Context}]{\setlength{\rightskip}{0pt plus 5cm}get\+Context (
\begin{DoxyParamCaption}
{}
\end{DoxyParamCaption}
)}\label{class_symfony_1_1_component_1_1_debug_1_1_exception_1_1_context_error_exception_a51609a8c7faaf9948679e3a291ba4733}
\begin{DoxyReturn}{Returns}
array Array of variables that existed when the exception occurred 
\end{DoxyReturn}


Definition at line 32 of file Context\+Error\+Exception.\+php.



The documentation for this class was generated from the following file\+:\begin{DoxyCompactItemize}
\item 
vendor/symfony/debug/\+Symfony/\+Component/\+Debug/\+Exception/{\bf Context\+Error\+Exception.\+php}\end{DoxyCompactItemize}
