.TH "PHPUnit_Framework_TestFailure" 3 "Tue Apr 14 2015" "Version 1.0" "VirtualSCADA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PHPUnit_Framework_TestFailure \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBPHPUnit_Framework_Test\fP $\fBfailedTest\fP, Exception $\fBthrownException\fP)"
.br
.ti -1c
.RI "\fBtoString\fP ()"
.br
.ti -1c
.RI "\fBgetExceptionAsString\fP ()"
.br
.ti -1c
.RI "\fBgetTestName\fP ()"
.br
.ti -1c
.RI "\fBfailedTest\fP ()"
.br
.ti -1c
.RI "\fBthrownException\fP ()"
.br
.ti -1c
.RI "\fBexceptionMessage\fP ()"
.br
.ti -1c
.RI "\fBisFailure\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBexceptionToString\fP (Exception $\fBe\fP)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$failedTest\fP"
.br
.ti -1c
.RI "\fB$thrownException\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 22 of file TestFailure\&.php\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "__construct (\fBPHPUnit_Framework_Test\fP $failedTest, Exception $thrownException)"
Constructs a TestFailure with the given test and exception\&.
.PP
\fBParameters:\fP
.RS 4
\fI$failedTest\fP 
.br
\fI$thrownException\fP 
.RE
.PP

.PP
Definition at line 45 of file TestFailure\&.php\&.
.SH "Member Function Documentation"
.PP 
.SS "exceptionMessage ()"
Returns the exception's message\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 154 of file TestFailure\&.php\&.
.SS "static exceptionToString (Exception $e)\fC [static]\fP"
Returns a description for an exception\&.
.PP
\fBParameters:\fP
.RS 4
\fI$e\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP
\fBSince:\fP
.RS 4
Method available since Release 3\&.2\&.0 
.RE
.PP

.PP
Definition at line 90 of file TestFailure\&.php\&.
.SS "failedTest ()"
Returns the failing test\&.
.PP
Note: The test object is not set when the test is executed in process isolation\&.
.PP
\fBSee also:\fP
.RS 4
\fBPHPUnit_Framework_Exception\fP
.RE
.PP
\fBReturns:\fP
.RS 4
PHPUnit_Framework_Test|null 
.RE
.PP

.PP
Definition at line 134 of file TestFailure\&.php\&.
.SS "getExceptionAsString ()"
Returns a description for the thrown exception\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP
\fBSince:\fP
.RS 4
Method available since Release 3\&.4\&.0 
.RE
.PP

.PP
Definition at line 78 of file TestFailure\&.php\&.
.SS "getTestName ()"
Returns the name of the failing test (including data set, if any)\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP
\fBSince:\fP
.RS 4
Method available since Release 4\&.3\&.0 
.RE
.PP

.PP
Definition at line 119 of file TestFailure\&.php\&.
.SS "isFailure ()"
Returns true if the thrown exception is of type AssertionFailedError\&.
.PP
\fBReturns:\fP
.RS 4
boolean 
.RE
.PP

.PP
Definition at line 165 of file TestFailure\&.php\&.
.SS "thrownException ()"
Gets the thrown exception\&.
.PP
\fBReturns:\fP
.RS 4
Exception 
.RE
.PP

.PP
Definition at line 144 of file TestFailure\&.php\&.
.SS "toString ()"
Returns a short description of the failure\&.
.PP
\fBReturns:\fP
.RS 4
string 
.RE
.PP

.PP
Definition at line 63 of file TestFailure\&.php\&.
.SH "Field Documentation"
.PP 
.SS "$\fBfailedTest\fP\fC [protected]\fP"

.PP
Definition at line 32 of file TestFailure\&.php\&.
.SS "$\fBthrownException\fP\fC [protected]\fP"

.PP
Definition at line 37 of file TestFailure\&.php\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VirtualSCADA from the source code\&.
